FROM golang:1.12-alpine

ARG ENVIRONMENT=DEV
ARG MONGODB_URI=mongodb://192.168.1.7:27017
ARG MONGODB_COLLECTION=product
ARG MONGODB_TIMEOUT=5
ARG PRODUCT_SERVER_PORT=:8082
ARG GRPC_PORT=3002
ARG MONGODB_HOST=192.168.1.7
ARG MONGODB_PORT=27017

ENV ENVIRONMENT=${ENVIRONMENT}
ENV MONGODB_URI=${MONGODB_URI}
ENV MONGODB_COLLECTION=${MONGODB_COLLECTION}
ENV MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
ENV PRODUCT_SERVER_PORT=${PRODUCT_SERVER_PORT}
ENV GRPC_PORT=${GRPC_PORT}

RUN apk add --no-cache git

RUN mkdir /app
COPY . /app

WORKDIR /app
RUN go mod download

WORKDIR /app/cmd

RUN go build -o main .
CMD ["/app/cmd/main"]